name: Generate and Deploy Feeds

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allows manual trigger from GitHub UI

permissions:
  contents: write  # Needed for pushing changes to the repository

env:
  USERNAME: Reisonancia
  PER_PAGE: 20

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Load Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate feeds
      run: |
        python script.py

    - name: Check generated files
      run: |
        echo "Generated files:"
        cat anilist-anime-20.xml  # Check content of anime file
        cat anilist-manga-20.xml  # Check content of manga file

    - name: Commit generated anime feeds
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add "Anime Feeds/anilist-anime-20.xml"
        git commit -m "Update Anime Feeds" || echo "No changes to commit"

    - name: Commit generated manga feeds
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add "Manga Feeds/anilist-manga-20.xml"
        git commit -m "Update Manga Feeds" || echo "No changes to commit"

    - name: Set Git remote with access token
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/LightCircleLLC/AniList-RSS.git

    - name: Push changes
      run: |
        git push origin main
