name: Generate and Deploy Feeds

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Run every hour

env:
  USERNAME: ${{ vars.USERNAME }}

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Load Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate feeds and deploy
      run: |
        python script.py

    - name: Commit generated feeds
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add feeds/*.xml
        git commit -m "Update RSS feeds"
        git push