name: Generate and Deploy Feeds

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allows manual trigger from GitHub UI

env:
  USERNAME: Reisonancia
  PER_PAGE: 20

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Load Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate feeds
      run: |
        python script.py

    - name: Commit generated anime feeds
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add feeds/Anime\ Feeds/*.xml
        git commit -m "Update Anime Feeds"

    - name: Commit generated manga feeds
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add feeds/Manga\ Feeds/*.xml
        git commit -m "Update Manga Feeds"

    - name: Push changes
      env:
        TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/LightCircleLLC/AniList-RSS.git
        git push origin main
